MT_Datasets:
  - dataname: nyud
    noniid: False
    client_num: 1
    local_epochs: 4
    tr_batch: 4
    val_batch: 4
    nworkers: 4
    lr: 0.0001
    weight_decay: 0.0001
    warmup_epochs: 5
    task_dict:
      semseg: 0
      normals: 1
      edge: 1
      depth: 0
  - dataname: pascalcontext
    noniid: False
    client_num: 1
    local_epochs: 1
    tr_batch: 4
    val_batch: 4
    nworkers: 4
    lr: 0.0001
    weight_decay: 0.0001
    warmup_epochs: 5
    task_dict:
      semseg: 0
      human_parts: 0
      normals: 1
      edge: 1
      sal: 0
    
Model:
  n_class: 3
  n_fc: 8
  dim_latent: 120